// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file model/memo/reaction.proto (package memo, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/memo/reaction.proto.
 */
export const file_model_memo_reaction: GenFile = /*@__PURE__*/
  fileDesc("Chltb2RlbC9tZW1vL3JlYWN0aW9uLnByb3RvEgRtZW1vIlIKCFJlYWN0aW9uEgoKAmlkGAEgASgFEg8KB2NyZWF0b3IYAiABKAkSEgoKY29udGVudF9pZBgDIAEoCRIVCg1yZWFjdGlvbl90eXBlGAQgASgJQjdaNWdpdGh1Yi5jb20vc21hcnRtZW1vcy9tZW1vcy9pbnRlcm5hbC9wcm90by9tb2RlbC9tZW1vYgZwcm90bzM", [file_google_protobuf_timestamp, file_google_api_field_behavior]);

/**
 * @generated from message memo.Reaction
 */
export type Reaction = Message<"memo.Reaction"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * The name of the creator.
   * Format: users/{user}
   *
   * @generated from field: string creator = 2;
   */
  creator: string;

  /**
   * The content identifier.
   * For memo, it should be the `Memo.name`.
   *
   * @generated from field: string content_id = 3;
   */
  contentId: string;

  /**
   * @generated from field: string reaction_type = 4;
   */
  reactionType: string;
};

/**
 * Describes the message memo.Reaction.
 * Use `create(ReactionSchema)` to create a new message.
 */
export const ReactionSchema: GenMessage<Reaction> = /*@__PURE__*/
  messageDesc(file_model_memo_reaction, 0);

