// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file model/memo/resource.proto (package memo, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/memo/resource.proto.
 */
export const file_model_memo_resource: GenFile = /*@__PURE__*/
  fileDesc("Chltb2RlbC9tZW1vL3Jlc291cmNlLnByb3RvEgRtZW1vItMBCghSZXNvdXJjZRIUCgRuYW1lGAEgASgJQgbgQQPgQQgSNAoLY3JlYXRlX3RpbWUYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQgPgQQMSEAoIZmlsZW5hbWUYBCABKAkSFAoHY29udGVudBgFIAEoDEID4EEEEhUKDWV4dGVybmFsX2xpbmsYBiABKAkSDAoEdHlwZRgHIAEoCRIMCgRzaXplGAggASgDEhEKBG1lbW8YCSABKAlIAIgBAUIHCgVfbWVtb0oECAIQA0I3WjVnaXRodWIuY29tL3NtYXJ0bWVtb3MvbWVtb3MvaW50ZXJuYWwvcHJvdG8vbW9kZWwvbWVtb2IGcHJvdG8z", [file_google_protobuf_timestamp, file_google_api_field_behavior]);

/**
 * @generated from message memo.Resource
 */
export type Resource = Message<"memo.Resource"> & {
  /**
   * The name of the resource.
   * Format: resources/{resource}, resource is the user defined if or uuid.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 3;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: string filename = 4;
   */
  filename: string;

  /**
   * @generated from field: bytes content = 5;
   */
  content: Uint8Array;

  /**
   * @generated from field: string external_link = 6;
   */
  externalLink: string;

  /**
   * @generated from field: string type = 7;
   */
  type: string;

  /**
   * @generated from field: int64 size = 8;
   */
  size: bigint;

  /**
   * The related memo. Refer to `Memo.name`.
   *
   * @generated from field: optional string memo = 9;
   */
  memo?: string;
};

/**
 * Describes the message memo.Resource.
 * Use `create(ResourceSchema)` to create a new message.
 */
export const ResourceSchema: GenMessage<Resource> = /*@__PURE__*/
  messageDesc(file_model_memo_resource, 0);

