// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v2/auth.proto

package v2

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "api.v2.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceCreateSessionProcedure is the fully-qualified name of the AuthService's CreateSession
	// RPC.
	AuthServiceCreateSessionProcedure = "/api.v2.AuthService/CreateSession"
)

// AuthServiceClient is a client for the api.v2.AuthService service.
type AuthServiceClient interface {
	// CreateSession authenticates a user and creates a new session.
	// Returns the authenticated user information upon successful authentication.
	CreateSession(context.Context, *connect.Request[CreateSessionRequest]) (*connect.Response[CreateSessionResponse], error)
}

// NewAuthServiceClient constructs a client for the api.v2.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := File_api_v2_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		createSession: connect.NewClient[CreateSessionRequest, CreateSessionResponse](
			httpClient,
			baseURL+AuthServiceCreateSessionProcedure,
			connect.WithSchema(authServiceMethods.ByName("CreateSession")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	createSession *connect.Client[CreateSessionRequest, CreateSessionResponse]
}

// CreateSession calls api.v2.AuthService.CreateSession.
func (c *authServiceClient) CreateSession(ctx context.Context, req *connect.Request[CreateSessionRequest]) (*connect.Response[CreateSessionResponse], error) {
	return c.createSession.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the api.v2.AuthService service.
type AuthServiceHandler interface {
	// CreateSession authenticates a user and creates a new session.
	// Returns the authenticated user information upon successful authentication.
	CreateSession(context.Context, *connect.Request[CreateSessionRequest]) (*connect.Response[CreateSessionResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := File_api_v2_auth_proto.Services().ByName("AuthService").Methods()
	authServiceCreateSessionHandler := connect.NewUnaryHandler(
		AuthServiceCreateSessionProcedure,
		svc.CreateSession,
		connect.WithSchema(authServiceMethods.ByName("CreateSession")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v2.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceCreateSessionProcedure:
			authServiceCreateSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) CreateSession(context.Context, *connect.Request[CreateSessionRequest]) (*connect.Response[CreateSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v2.AuthService.CreateSession is not implemented"))
}
