// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v2/inbox.proto

package v2

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InboxServiceName is the fully-qualified name of the InboxService service.
	InboxServiceName = "api.v2.InboxService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InboxServiceListInboxesProcedure is the fully-qualified name of the InboxService's ListInboxes
	// RPC.
	InboxServiceListInboxesProcedure = "/api.v2.InboxService/ListInboxes"
)

// InboxServiceClient is a client for the api.v2.InboxService service.
type InboxServiceClient interface {
	// ListInboxes lists inboxes for a user.
	ListInboxes(context.Context, *connect.Request[ListInboxesRequest]) (*connect.Response[ListInboxesResponse], error)
}

// NewInboxServiceClient constructs a client for the api.v2.InboxService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInboxServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InboxServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	inboxServiceMethods := File_api_v2_inbox_proto.Services().ByName("InboxService").Methods()
	return &inboxServiceClient{
		listInboxes: connect.NewClient[ListInboxesRequest, ListInboxesResponse](
			httpClient,
			baseURL+InboxServiceListInboxesProcedure,
			connect.WithSchema(inboxServiceMethods.ByName("ListInboxes")),
			connect.WithClientOptions(opts...),
		),
	}
}

// inboxServiceClient implements InboxServiceClient.
type inboxServiceClient struct {
	listInboxes *connect.Client[ListInboxesRequest, ListInboxesResponse]
}

// ListInboxes calls api.v2.InboxService.ListInboxes.
func (c *inboxServiceClient) ListInboxes(ctx context.Context, req *connect.Request[ListInboxesRequest]) (*connect.Response[ListInboxesResponse], error) {
	return c.listInboxes.CallUnary(ctx, req)
}

// InboxServiceHandler is an implementation of the api.v2.InboxService service.
type InboxServiceHandler interface {
	// ListInboxes lists inboxes for a user.
	ListInboxes(context.Context, *connect.Request[ListInboxesRequest]) (*connect.Response[ListInboxesResponse], error)
}

// NewInboxServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInboxServiceHandler(svc InboxServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	inboxServiceMethods := File_api_v2_inbox_proto.Services().ByName("InboxService").Methods()
	inboxServiceListInboxesHandler := connect.NewUnaryHandler(
		InboxServiceListInboxesProcedure,
		svc.ListInboxes,
		connect.WithSchema(inboxServiceMethods.ByName("ListInboxes")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v2.InboxService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InboxServiceListInboxesProcedure:
			inboxServiceListInboxesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInboxServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInboxServiceHandler struct{}

func (UnimplementedInboxServiceHandler) ListInboxes(context.Context, *connect.Request[ListInboxesRequest]) (*connect.Response[ListInboxesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v2.InboxService.ListInboxes is not implemented"))
}
