// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v2/markdown.proto

package v2

import (
	connect "connectrpc.com/connect"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MarkdownServiceName is the fully-qualified name of the MarkdownService service.
	MarkdownServiceName = "api.v2.MarkdownService"
)

// MarkdownServiceClient is a client for the api.v2.MarkdownService service.
type MarkdownServiceClient interface {
}

// NewMarkdownServiceClient constructs a client for the api.v2.MarkdownService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMarkdownServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MarkdownServiceClient {
	return &markdownServiceClient{}
}

// markdownServiceClient implements MarkdownServiceClient.
type markdownServiceClient struct {
}

// MarkdownServiceHandler is an implementation of the api.v2.MarkdownService service.
type MarkdownServiceHandler interface {
}

// NewMarkdownServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMarkdownServiceHandler(svc MarkdownServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	return "/api.v2.MarkdownService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMarkdownServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMarkdownServiceHandler struct{}
