// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/v2/user.proto

package v2

import (
	model "github.com/smartmemos/memos/internal/proto/model"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The user to create.
	User          *model.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_v2_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_v2_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUser() *model.User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_api_v2_user_proto protoreflect.FileDescriptor

const file_api_v2_user_proto_rawDesc = "" +
	"\n" +
	"\x11api/v2/user.proto\x12\x06api.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10model/user.proto\"4\n" +
	"\x11CreateUserRequest\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.model.UserR\x04user2E\n" +
	"\vUserService\x126\n" +
	"\n" +
	"CreateUser\x12\x19.api.v2.CreateUserRequest\x1a\v.model.User\"\x00B3Z1github.com/smartmemos/memos/internal/proto/api/v2b\x06proto3"

var (
	file_api_v2_user_proto_rawDescOnce sync.Once
	file_api_v2_user_proto_rawDescData []byte
)

func file_api_v2_user_proto_rawDescGZIP() []byte {
	file_api_v2_user_proto_rawDescOnce.Do(func() {
		file_api_v2_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v2_user_proto_rawDesc), len(file_api_v2_user_proto_rawDesc)))
	})
	return file_api_v2_user_proto_rawDescData
}

var file_api_v2_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_v2_user_proto_goTypes = []any{
	(*CreateUserRequest)(nil), // 0: api.v2.CreateUserRequest
	(*model.User)(nil),        // 1: model.User
}
var file_api_v2_user_proto_depIdxs = []int32{
	1, // 0: api.v2.CreateUserRequest.user:type_name -> model.User
	0, // 1: api.v2.UserService.CreateUser:input_type -> api.v2.CreateUserRequest
	1, // 2: api.v2.UserService.CreateUser:output_type -> model.User
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v2_user_proto_init() }
func file_api_v2_user_proto_init() {
	if File_api_v2_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v2_user_proto_rawDesc), len(file_api_v2_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v2_user_proto_goTypes,
		DependencyIndexes: file_api_v2_user_proto_depIdxs,
		MessageInfos:      file_api_v2_user_proto_msgTypes,
	}.Build()
	File_api_v2_user_proto = out.File
	file_api_v2_user_proto_goTypes = nil
	file_api_v2_user_proto_depIdxs = nil
}
