// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/v2/webhook.proto

package v2

import (
	model "github.com/smartmemos/memos/internal/proto/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListWebhooksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The parent resource where webhooks are listed.
	// Format: users/{user}
	Parent        string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksRequest) Reset() {
	*x = ListWebhooksRequest{}
	mi := &file_api_v2_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksRequest) ProtoMessage() {}

func (x *ListWebhooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksRequest.ProtoReflect.Descriptor instead.
func (*ListWebhooksRequest) Descriptor() ([]byte, []int) {
	return file_api_v2_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *ListWebhooksRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type ListWebhooksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of webhooks.
	Webhooks      []*model.Webhook `protobuf:"bytes,1,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksResponse) Reset() {
	*x = ListWebhooksResponse{}
	mi := &file_api_v2_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksResponse) ProtoMessage() {}

func (x *ListWebhooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksResponse.ProtoReflect.Descriptor instead.
func (*ListWebhooksResponse) Descriptor() ([]byte, []int) {
	return file_api_v2_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *ListWebhooksResponse) GetWebhooks() []*model.Webhook {
	if x != nil {
		return x.Webhooks
	}
	return nil
}

type GetWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the webhook to retrieve.
	// Format: users/{user}/webhooks/{webhook}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookRequest) Reset() {
	*x = GetWebhookRequest{}
	mi := &file_api_v2_webhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookRequest) ProtoMessage() {}

func (x *GetWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_webhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookRequest.ProtoReflect.Descriptor instead.
func (*GetWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_v2_webhook_proto_rawDescGZIP(), []int{2}
}

func (x *GetWebhookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The parent resource where this webhook will be created.
	// Format: users/{user}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Required. The webhook to create.
	Webhook *model.Webhook `protobuf:"bytes,2,opt,name=webhook,proto3" json:"webhook,omitempty"`
	// Optional. If set, validate the request, but do not actually create the webhook.
	ValidateOnly  bool `protobuf:"varint,3,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebhookRequest) Reset() {
	*x = CreateWebhookRequest{}
	mi := &file_api_v2_webhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebhookRequest) ProtoMessage() {}

func (x *CreateWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_webhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebhookRequest.ProtoReflect.Descriptor instead.
func (*CreateWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_v2_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWebhookRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateWebhookRequest) GetWebhook() *model.Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

func (x *CreateWebhookRequest) GetValidateOnly() bool {
	if x != nil {
		return x.ValidateOnly
	}
	return false
}

type UpdateWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The webhook resource which replaces the resource on the server.
	Webhook *model.Webhook `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	// Optional. The list of fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWebhookRequest) Reset() {
	*x = UpdateWebhookRequest{}
	mi := &file_api_v2_webhook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebhookRequest) ProtoMessage() {}

func (x *UpdateWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_webhook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebhookRequest.ProtoReflect.Descriptor instead.
func (*UpdateWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_v2_webhook_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateWebhookRequest) GetWebhook() *model.Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

func (x *UpdateWebhookRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the webhook to delete.
	// Format: users/{user}/webhooks/{webhook}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookRequest) Reset() {
	*x = DeleteWebhookRequest{}
	mi := &file_api_v2_webhook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookRequest) ProtoMessage() {}

func (x *DeleteWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v2_webhook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookRequest.ProtoReflect.Descriptor instead.
func (*DeleteWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_v2_webhook_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteWebhookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_v2_webhook_proto protoreflect.FileDescriptor

const file_api_v2_webhook_proto_rawDesc = "" +
	"\n" +
	"\x14api/v2/webhook.proto\x12\x06api.v2\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x13model/webhook.proto\"-\n" +
	"\x13ListWebhooksRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\"B\n" +
	"\x14ListWebhooksResponse\x12*\n" +
	"\bwebhooks\x18\x01 \x03(\v2\x0e.model.WebhookR\bwebhooks\"'\n" +
	"\x11GetWebhookRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"}\n" +
	"\x14CreateWebhookRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12(\n" +
	"\awebhook\x18\x02 \x01(\v2\x0e.model.WebhookR\awebhook\x12#\n" +
	"\rvalidate_only\x18\x03 \x01(\bR\fvalidateOnly\"}\n" +
	"\x14UpdateWebhookRequest\x12(\n" +
	"\awebhook\x18\x01 \x01(\v2\x0e.model.WebhookR\awebhook\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"*\n" +
	"\x14DeleteWebhookRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xe3\x02\n" +
	"\x0eWebhookService\x12K\n" +
	"\fListWebhooks\x12\x1b.api.v2.ListWebhooksRequest\x1a\x1c.api.v2.ListWebhooksResponse\"\x00\x129\n" +
	"\n" +
	"GetWebhook\x12\x19.api.v2.GetWebhookRequest\x1a\x0e.model.Webhook\"\x00\x12?\n" +
	"\rCreateWebhook\x12\x1c.api.v2.CreateWebhookRequest\x1a\x0e.model.Webhook\"\x00\x12?\n" +
	"\rUpdateWebhook\x12\x1c.api.v2.UpdateWebhookRequest\x1a\x0e.model.Webhook\"\x00\x12G\n" +
	"\rDeleteWebhook\x12\x1c.api.v2.DeleteWebhookRequest\x1a\x16.google.protobuf.Empty\"\x00B3Z1github.com/smartmemos/memos/internal/proto/api/v2b\x06proto3"

var (
	file_api_v2_webhook_proto_rawDescOnce sync.Once
	file_api_v2_webhook_proto_rawDescData []byte
)

func file_api_v2_webhook_proto_rawDescGZIP() []byte {
	file_api_v2_webhook_proto_rawDescOnce.Do(func() {
		file_api_v2_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v2_webhook_proto_rawDesc), len(file_api_v2_webhook_proto_rawDesc)))
	})
	return file_api_v2_webhook_proto_rawDescData
}

var file_api_v2_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_v2_webhook_proto_goTypes = []any{
	(*ListWebhooksRequest)(nil),   // 0: api.v2.ListWebhooksRequest
	(*ListWebhooksResponse)(nil),  // 1: api.v2.ListWebhooksResponse
	(*GetWebhookRequest)(nil),     // 2: api.v2.GetWebhookRequest
	(*CreateWebhookRequest)(nil),  // 3: api.v2.CreateWebhookRequest
	(*UpdateWebhookRequest)(nil),  // 4: api.v2.UpdateWebhookRequest
	(*DeleteWebhookRequest)(nil),  // 5: api.v2.DeleteWebhookRequest
	(*model.Webhook)(nil),         // 6: model.Webhook
	(*fieldmaskpb.FieldMask)(nil), // 7: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_api_v2_webhook_proto_depIdxs = []int32{
	6, // 0: api.v2.ListWebhooksResponse.webhooks:type_name -> model.Webhook
	6, // 1: api.v2.CreateWebhookRequest.webhook:type_name -> model.Webhook
	6, // 2: api.v2.UpdateWebhookRequest.webhook:type_name -> model.Webhook
	7, // 3: api.v2.UpdateWebhookRequest.update_mask:type_name -> google.protobuf.FieldMask
	0, // 4: api.v2.WebhookService.ListWebhooks:input_type -> api.v2.ListWebhooksRequest
	2, // 5: api.v2.WebhookService.GetWebhook:input_type -> api.v2.GetWebhookRequest
	3, // 6: api.v2.WebhookService.CreateWebhook:input_type -> api.v2.CreateWebhookRequest
	4, // 7: api.v2.WebhookService.UpdateWebhook:input_type -> api.v2.UpdateWebhookRequest
	5, // 8: api.v2.WebhookService.DeleteWebhook:input_type -> api.v2.DeleteWebhookRequest
	1, // 9: api.v2.WebhookService.ListWebhooks:output_type -> api.v2.ListWebhooksResponse
	6, // 10: api.v2.WebhookService.GetWebhook:output_type -> model.Webhook
	6, // 11: api.v2.WebhookService.CreateWebhook:output_type -> model.Webhook
	6, // 12: api.v2.WebhookService.UpdateWebhook:output_type -> model.Webhook
	8, // 13: api.v2.WebhookService.DeleteWebhook:output_type -> google.protobuf.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v2_webhook_proto_init() }
func file_api_v2_webhook_proto_init() {
	if File_api_v2_webhook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v2_webhook_proto_rawDesc), len(file_api_v2_webhook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v2_webhook_proto_goTypes,
		DependencyIndexes: file_api_v2_webhook_proto_depIdxs,
		MessageInfos:      file_api_v2_webhook_proto_msgTypes,
	}.Build()
	File_api_v2_webhook_proto = out.File
	file_api_v2_webhook_proto_goTypes = nil
	file_api_v2_webhook_proto_depIdxs = nil
}
