version: "3.8"
services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    restart: unless-stopped
    ports:
      - "5230:5230"
    volumes:
      - ./data:/var/opt/memos
    environment:
      - MEMOS_MODE=dev
      - MEMOS_PORT=5230
      - MEMOS_DRIVER=${MEMOS_DRIVER}
      - MEMOS_DSN=${MEMOS_DSN}
