// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: model/memo/memo.proto

package memo

import (
	common "github.com/smartmemos/memos/internal/proto/model/common"
	markdown "github.com/smartmemos/memos/internal/proto/model/markdown"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Visibility int32

const (
	Visibility_VISIBILITY_UNSPECIFIED Visibility = 0
	Visibility_PRIVATE                Visibility = 1
	Visibility_PROTECTED              Visibility = 2
	Visibility_PUBLIC                 Visibility = 3
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "PRIVATE",
		2: "PROTECTED",
		3: "PUBLIC",
	}
	Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED": 0,
		"PRIVATE":                1,
		"PROTECTED":              2,
		"PUBLIC":                 3,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_model_memo_memo_proto_enumTypes[0].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_model_memo_memo_proto_enumTypes[0]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_model_memo_memo_proto_rawDescGZIP(), []int{0}
}

type MemoRelation_Type int32

const (
	MemoRelation_TYPE_UNSPECIFIED MemoRelation_Type = 0
	MemoRelation_REFERENCE        MemoRelation_Type = 1
	MemoRelation_COMMENT          MemoRelation_Type = 2
)

// Enum value maps for MemoRelation_Type.
var (
	MemoRelation_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "REFERENCE",
		2: "COMMENT",
	}
	MemoRelation_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"REFERENCE":        1,
		"COMMENT":          2,
	}
)

func (x MemoRelation_Type) Enum() *MemoRelation_Type {
	p := new(MemoRelation_Type)
	*p = x
	return p
}

func (x MemoRelation_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemoRelation_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_model_memo_memo_proto_enumTypes[1].Descriptor()
}

func (MemoRelation_Type) Type() protoreflect.EnumType {
	return &file_model_memo_memo_proto_enumTypes[1]
}

func (x MemoRelation_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemoRelation_Type.Descriptor instead.
func (MemoRelation_Type) EnumDescriptor() ([]byte, []int) {
	return file_model_memo_memo_proto_rawDescGZIP(), []int{2, 0}
}

type Memo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the memo.
	// Format: memos/{memo}, memo is the user defined id or uuid.
	Name  string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State common.State `protobuf:"varint,3,opt,name=state,proto3,enum=common.State" json:"state,omitempty"`
	// The name of the creator.
	// Format: users/{user}
	Creator     string                 `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	CreateTime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	DisplayTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=display_time,json=displayTime,proto3" json:"display_time,omitempty"`
	Content     string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	Nodes       []*markdown.Node       `protobuf:"bytes,9,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Visibility  Visibility             `protobuf:"varint,10,opt,name=visibility,proto3,enum=memo.Visibility" json:"visibility,omitempty"`
	Tags        []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	Pinned      bool                   `protobuf:"varint,12,opt,name=pinned,proto3" json:"pinned,omitempty"`
	Resources   []*Resource            `protobuf:"bytes,14,rep,name=resources,proto3" json:"resources,omitempty"`
	Relations   []*MemoRelation        `protobuf:"bytes,15,rep,name=relations,proto3" json:"relations,omitempty"`
	Reactions   []*Reaction            `protobuf:"bytes,16,rep,name=reactions,proto3" json:"reactions,omitempty"`
	Property    *Memo_Property         `protobuf:"bytes,17,opt,name=property,proto3" json:"property,omitempty"`
	// The name of the parent memo.
	// Format: memos/{id}
	Parent *string `protobuf:"bytes,18,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	// The snippet of the memo content. Plain text only.
	Snippet string `protobuf:"bytes,19,opt,name=snippet,proto3" json:"snippet,omitempty"`
	// The location of the memo.
	Location      *Location `protobuf:"bytes,20,opt,name=location,proto3,oneof" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memo) Reset() {
	*x = Memo{}
	mi := &file_model_memo_memo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memo) ProtoMessage() {}

func (x *Memo) ProtoReflect() protoreflect.Message {
	mi := &file_model_memo_memo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memo.ProtoReflect.Descriptor instead.
func (*Memo) Descriptor() ([]byte, []int) {
	return file_model_memo_memo_proto_rawDescGZIP(), []int{0}
}

func (x *Memo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Memo) GetState() common.State {
	if x != nil {
		return x.State
	}
	return common.State(0)
}

func (x *Memo) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Memo) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Memo) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Memo) GetDisplayTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DisplayTime
	}
	return nil
}

func (x *Memo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Memo) GetNodes() []*markdown.Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Memo) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

func (x *Memo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Memo) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *Memo) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Memo) GetRelations() []*MemoRelation {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *Memo) GetReactions() []*Reaction {
	if x != nil {
		return x.Reactions
	}
	return nil
}

func (x *Memo) GetProperty() *Memo_Property {
	if x != nil {
		return x.Property
	}
	return nil
}

func (x *Memo) GetParent() string {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return ""
}

func (x *Memo) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *Memo) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   string                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_model_memo_memo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_model_memo_memo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_model_memo_memo_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type MemoRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memo          *MemoRelation_Memo     `protobuf:"bytes,1,opt,name=memo,proto3" json:"memo,omitempty"`
	RelatedMemo   *MemoRelation_Memo     `protobuf:"bytes,2,opt,name=related_memo,json=relatedMemo,proto3" json:"related_memo,omitempty"`
	Type          MemoRelation_Type      `protobuf:"varint,3,opt,name=type,proto3,enum=memo.MemoRelation_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoRelation) Reset() {
	*x = MemoRelation{}
	mi := &file_model_memo_memo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoRelation) ProtoMessage() {}

func (x *MemoRelation) ProtoReflect() protoreflect.Message {
	mi := &file_model_memo_memo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoRelation.ProtoReflect.Descriptor instead.
func (*MemoRelation) Descriptor() ([]byte, []int) {
	return file_model_memo_memo_proto_rawDescGZIP(), []int{2}
}

func (x *MemoRelation) GetMemo() *MemoRelation_Memo {
	if x != nil {
		return x.Memo
	}
	return nil
}

func (x *MemoRelation) GetRelatedMemo() *MemoRelation_Memo {
	if x != nil {
		return x.RelatedMemo
	}
	return nil
}

func (x *MemoRelation) GetType() MemoRelation_Type {
	if x != nil {
		return x.Type
	}
	return MemoRelation_TYPE_UNSPECIFIED
}

type Memo_Property struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HasLink            bool                   `protobuf:"varint,1,opt,name=has_link,json=hasLink,proto3" json:"has_link,omitempty"`
	HasTaskList        bool                   `protobuf:"varint,2,opt,name=has_task_list,json=hasTaskList,proto3" json:"has_task_list,omitempty"`
	HasCode            bool                   `protobuf:"varint,3,opt,name=has_code,json=hasCode,proto3" json:"has_code,omitempty"`
	HasIncompleteTasks bool                   `protobuf:"varint,4,opt,name=has_incomplete_tasks,json=hasIncompleteTasks,proto3" json:"has_incomplete_tasks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Memo_Property) Reset() {
	*x = Memo_Property{}
	mi := &file_model_memo_memo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memo_Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memo_Property) ProtoMessage() {}

func (x *Memo_Property) ProtoReflect() protoreflect.Message {
	mi := &file_model_memo_memo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memo_Property.ProtoReflect.Descriptor instead.
func (*Memo_Property) Descriptor() ([]byte, []int) {
	return file_model_memo_memo_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Memo_Property) GetHasLink() bool {
	if x != nil {
		return x.HasLink
	}
	return false
}

func (x *Memo_Property) GetHasTaskList() bool {
	if x != nil {
		return x.HasTaskList
	}
	return false
}

func (x *Memo_Property) GetHasCode() bool {
	if x != nil {
		return x.HasCode
	}
	return false
}

func (x *Memo_Property) GetHasIncompleteTasks() bool {
	if x != nil {
		return x.HasIncompleteTasks
	}
	return false
}

type MemoRelation_Memo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the memo.
	// Format: memos/{id}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid  string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// The snippet of the memo content. Plain text only.
	Snippet       string `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoRelation_Memo) Reset() {
	*x = MemoRelation_Memo{}
	mi := &file_model_memo_memo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoRelation_Memo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoRelation_Memo) ProtoMessage() {}

func (x *MemoRelation_Memo) ProtoReflect() protoreflect.Message {
	mi := &file_model_memo_memo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoRelation_Memo.ProtoReflect.Descriptor instead.
func (*MemoRelation_Memo) Descriptor() ([]byte, []int) {
	return file_model_memo_memo_proto_rawDescGZIP(), []int{2, 0}
}

func (x *MemoRelation_Memo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemoRelation_Memo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *MemoRelation_Memo) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

var File_model_memo_memo_proto protoreflect.FileDescriptor

const file_model_memo_memo_proto_rawDesc = "" +
	"\n" +
	"\x15model/memo/memo.proto\x12\x04memo\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19model/common/common.proto\x1a\x19model/memo/resource.proto\x1a\x19model/memo/reaction.proto\x1a\x1dmodel/markdown/markdown.proto\"\xb4\a\n" +
	"\x04Memo\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xe0A\x03\xe0A\bR\x04name\x12#\n" +
	"\x05state\x18\x03 \x01(\x0e2\r.common.StateR\x05state\x12\x18\n" +
	"\acreator\x18\x04 \x01(\tR\acreator\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12=\n" +
	"\fdisplay_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vdisplayTime\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12)\n" +
	"\x05nodes\x18\t \x03(\v2\x0e.markdown.NodeB\x03\xe0A\x03R\x05nodes\x120\n" +
	"\n" +
	"visibility\x18\n" +
	" \x01(\x0e2\x10.memo.VisibilityR\n" +
	"visibility\x12\x17\n" +
	"\x04tags\x18\v \x03(\tB\x03\xe0A\x03R\x04tags\x12\x16\n" +
	"\x06pinned\x18\f \x01(\bR\x06pinned\x12,\n" +
	"\tresources\x18\x0e \x03(\v2\x0e.memo.ResourceR\tresources\x120\n" +
	"\trelations\x18\x0f \x03(\v2\x12.memo.MemoRelationR\trelations\x121\n" +
	"\treactions\x18\x10 \x03(\v2\x0e.memo.ReactionB\x03\xe0A\x03R\treactions\x124\n" +
	"\bproperty\x18\x11 \x01(\v2\x13.memo.Memo.PropertyB\x03\xe0A\x03R\bproperty\x12 \n" +
	"\x06parent\x18\x12 \x01(\tB\x03\xe0A\x03H\x00R\x06parent\x88\x01\x01\x12\x1d\n" +
	"\asnippet\x18\x13 \x01(\tB\x03\xe0A\x03R\asnippet\x12/\n" +
	"\blocation\x18\x14 \x01(\v2\x0e.memo.LocationH\x01R\blocation\x88\x01\x01\x1a\x96\x01\n" +
	"\bProperty\x12\x19\n" +
	"\bhas_link\x18\x01 \x01(\bR\ahasLink\x12\"\n" +
	"\rhas_task_list\x18\x02 \x01(\bR\vhasTaskList\x12\x19\n" +
	"\bhas_code\x18\x03 \x01(\bR\ahasCode\x120\n" +
	"\x14has_incomplete_tasks\x18\x04 \x01(\bR\x12hasIncompleteTasksB\t\n" +
	"\a_parentB\v\n" +
	"\t_locationJ\x04\b\x02\x10\x03\"f\n" +
	"\bLocation\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholder\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"\xab\x02\n" +
	"\fMemoRelation\x12+\n" +
	"\x04memo\x18\x01 \x01(\v2\x17.memo.MemoRelation.MemoR\x04memo\x12:\n" +
	"\frelated_memo\x18\x02 \x01(\v2\x17.memo.MemoRelation.MemoR\vrelatedMemo\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.memo.MemoRelation.TypeR\x04type\x1aK\n" +
	"\x04Memo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x1d\n" +
	"\asnippet\x18\x03 \x01(\tB\x03\xe0A\x03R\asnippet\"8\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tREFERENCE\x10\x01\x12\v\n" +
	"\aCOMMENT\x10\x02*P\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPRIVATE\x10\x01\x12\r\n" +
	"\tPROTECTED\x10\x02\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x03B7Z5github.com/smartmemos/memos/internal/proto/model/memob\x06proto3"

var (
	file_model_memo_memo_proto_rawDescOnce sync.Once
	file_model_memo_memo_proto_rawDescData []byte
)

func file_model_memo_memo_proto_rawDescGZIP() []byte {
	file_model_memo_memo_proto_rawDescOnce.Do(func() {
		file_model_memo_memo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_memo_memo_proto_rawDesc), len(file_model_memo_memo_proto_rawDesc)))
	})
	return file_model_memo_memo_proto_rawDescData
}

var file_model_memo_memo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_model_memo_memo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_model_memo_memo_proto_goTypes = []any{
	(Visibility)(0),               // 0: memo.Visibility
	(MemoRelation_Type)(0),        // 1: memo.MemoRelation.Type
	(*Memo)(nil),                  // 2: memo.Memo
	(*Location)(nil),              // 3: memo.Location
	(*MemoRelation)(nil),          // 4: memo.MemoRelation
	(*Memo_Property)(nil),         // 5: memo.Memo.Property
	(*MemoRelation_Memo)(nil),     // 6: memo.MemoRelation.Memo
	(common.State)(0),             // 7: common.State
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*markdown.Node)(nil),         // 9: markdown.Node
	(*Resource)(nil),              // 10: memo.Resource
	(*Reaction)(nil),              // 11: memo.Reaction
}
var file_model_memo_memo_proto_depIdxs = []int32{
	7,  // 0: memo.Memo.state:type_name -> common.State
	8,  // 1: memo.Memo.create_time:type_name -> google.protobuf.Timestamp
	8,  // 2: memo.Memo.update_time:type_name -> google.protobuf.Timestamp
	8,  // 3: memo.Memo.display_time:type_name -> google.protobuf.Timestamp
	9,  // 4: memo.Memo.nodes:type_name -> markdown.Node
	0,  // 5: memo.Memo.visibility:type_name -> memo.Visibility
	10, // 6: memo.Memo.resources:type_name -> memo.Resource
	4,  // 7: memo.Memo.relations:type_name -> memo.MemoRelation
	11, // 8: memo.Memo.reactions:type_name -> memo.Reaction
	5,  // 9: memo.Memo.property:type_name -> memo.Memo.Property
	3,  // 10: memo.Memo.location:type_name -> memo.Location
	6,  // 11: memo.MemoRelation.memo:type_name -> memo.MemoRelation.Memo
	6,  // 12: memo.MemoRelation.related_memo:type_name -> memo.MemoRelation.Memo
	1,  // 13: memo.MemoRelation.type:type_name -> memo.MemoRelation.Type
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_model_memo_memo_proto_init() }
func file_model_memo_memo_proto_init() {
	if File_model_memo_memo_proto != nil {
		return
	}
	file_model_memo_resource_proto_init()
	file_model_memo_reaction_proto_init()
	file_model_memo_memo_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_memo_memo_proto_rawDesc), len(file_model_memo_memo_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_memo_memo_proto_goTypes,
		DependencyIndexes: file_model_memo_memo_proto_depIdxs,
		EnumInfos:         file_model_memo_memo_proto_enumTypes,
		MessageInfos:      file_model_memo_memo_proto_msgTypes,
	}.Build()
	File_model_memo_memo_proto = out.File
	file_model_memo_memo_proto_goTypes = nil
	file_model_memo_memo_proto_depIdxs = nil
}
