// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/v1/workspace.proto

package v1

import (
	workspace "github.com/smartmemos/memos/internal/proto/model/workspace"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListIdentityProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdentityProvidersRequest) Reset() {
	*x = ListIdentityProvidersRequest{}
	mi := &file_api_v1_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdentityProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdentityProvidersRequest) ProtoMessage() {}

func (x *ListIdentityProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdentityProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListIdentityProvidersRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_workspace_proto_rawDescGZIP(), []int{0}
}

type ListIdentityProvidersResponse struct {
	state             protoimpl.MessageState        `protogen:"open.v1"`
	IdentityProviders []*workspace.IdentityProvider `protobuf:"bytes,1,rep,name=identity_providers,json=identityProviders,proto3" json:"identity_providers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListIdentityProvidersResponse) Reset() {
	*x = ListIdentityProvidersResponse{}
	mi := &file_api_v1_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdentityProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdentityProvidersResponse) ProtoMessage() {}

func (x *ListIdentityProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdentityProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListIdentityProvidersResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *ListIdentityProvidersResponse) GetIdentityProviders() []*workspace.IdentityProvider {
	if x != nil {
		return x.IdentityProviders
	}
	return nil
}

type GetIdentityProviderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the identityProvider to get.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdentityProviderRequest) Reset() {
	*x = GetIdentityProviderRequest{}
	mi := &file_api_v1_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdentityProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityProviderRequest) ProtoMessage() {}

func (x *GetIdentityProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityProviderRequest.ProtoReflect.Descriptor instead.
func (*GetIdentityProviderRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *GetIdentityProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetWorkspaceProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceProfileRequest) Reset() {
	*x = GetWorkspaceProfileRequest{}
	mi := &file_api_v1_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceProfileRequest) ProtoMessage() {}

func (x *GetWorkspaceProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceProfileRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_workspace_proto_rawDescGZIP(), []int{3}
}

type GetWorkspaceSettingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the workspace setting.
	// Format: settings/{setting}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceSettingRequest) Reset() {
	*x = GetWorkspaceSettingRequest{}
	mi := &file_api_v1_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceSettingRequest) ProtoMessage() {}

func (x *GetWorkspaceSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceSettingRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceSettingRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkspaceSettingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SetWorkspaceSettingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// setting is the setting to update.
	Setting       *workspace.Setting `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWorkspaceSettingRequest) Reset() {
	*x = SetWorkspaceSettingRequest{}
	mi := &file_api_v1_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWorkspaceSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWorkspaceSettingRequest) ProtoMessage() {}

func (x *SetWorkspaceSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWorkspaceSettingRequest.ProtoReflect.Descriptor instead.
func (*SetWorkspaceSettingRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *SetWorkspaceSettingRequest) GetSetting() *workspace.Setting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type ListInboxesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Format: users/{user}
	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// The maximum number of inbox to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Provide this to retrieve the subsequent page.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInboxesRequest) Reset() {
	*x = ListInboxesRequest{}
	mi := &file_api_v1_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInboxesRequest) ProtoMessage() {}

func (x *ListInboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInboxesRequest.ProtoReflect.Descriptor instead.
func (*ListInboxesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *ListInboxesRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ListInboxesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInboxesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListInboxesResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Inboxes []*workspace.Inbox     `protobuf:"bytes,1,rep,name=inboxes,proto3" json:"inboxes,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInboxesResponse) Reset() {
	*x = ListInboxesResponse{}
	mi := &file_api_v1_workspace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInboxesResponse) ProtoMessage() {}

func (x *ListInboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_workspace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInboxesResponse.ProtoReflect.Descriptor instead.
func (*ListInboxesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_workspace_proto_rawDescGZIP(), []int{7}
}

func (x *ListInboxesResponse) GetInboxes() []*workspace.Inbox {
	if x != nil {
		return x.Inboxes
	}
	return nil
}

func (x *ListInboxesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateInboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inbox         *workspace.Inbox       `protobuf:"bytes,1,opt,name=inbox,proto3" json:"inbox,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInboxRequest) Reset() {
	*x = UpdateInboxRequest{}
	mi := &file_api_v1_workspace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInboxRequest) ProtoMessage() {}

func (x *UpdateInboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_workspace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInboxRequest.ProtoReflect.Descriptor instead.
func (*UpdateInboxRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_workspace_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateInboxRequest) GetInbox() *workspace.Inbox {
	if x != nil {
		return x.Inbox
	}
	return nil
}

func (x *UpdateInboxRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteInboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the inbox to delete.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInboxRequest) Reset() {
	*x = DeleteInboxRequest{}
	mi := &file_api_v1_workspace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInboxRequest) ProtoMessage() {}

func (x *DeleteInboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_workspace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInboxRequest.ProtoReflect.Descriptor instead.
func (*DeleteInboxRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_workspace_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteInboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_v1_workspace_proto protoreflect.FileDescriptor

const file_api_v1_workspace_proto_rawDesc = "" +
	"\n" +
	"\x16api/v1/workspace.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x1dmodel/workspace/setting.proto\x1a\x1dmodel/workspace/profile.proto\x1a'model/workspace/identity_provider.proto\x1a\x1bmodel/workspace/inbox.proto\"\x1e\n" +
	"\x1cListIdentityProvidersRequest\"k\n" +
	"\x1dListIdentityProvidersResponse\x12J\n" +
	"\x12identity_providers\x18\x01 \x03(\v2\x1b.workspace.IdentityProviderR\x11identityProviders\"0\n" +
	"\x1aGetIdentityProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1c\n" +
	"\x1aGetWorkspaceProfileRequest\"5\n" +
	"\x1aGetWorkspaceSettingRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\"J\n" +
	"\x1aSetWorkspaceSettingRequest\x12,\n" +
	"\asetting\x18\x01 \x01(\v2\x12.workspace.SettingR\asetting\"d\n" +
	"\x12ListInboxesRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"i\n" +
	"\x13ListInboxesResponse\x12*\n" +
	"\ainboxes\x18\x01 \x03(\v2\x10.workspace.InboxR\ainboxes\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"y\n" +
	"\x12UpdateInboxRequest\x12&\n" +
	"\x05inbox\x18\x01 \x01(\v2\x10.workspace.InboxR\x05inbox\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"(\n" +
	"\x12DeleteInboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\x83\b\n" +
	"\x10WorkspaceService\x12p\n" +
	"\x13GetWorkspaceProfile\x12\".api.v1.GetWorkspaceProfileRequest\x1a\x12.workspace.Profile\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/workspace/profile\x12\x81\x01\n" +
	"\x13GetWorkspaceSetting\x12\".api.v1.GetWorkspaceSettingRequest\x1a\x12.workspace.Setting\"2\xdaA\x04name\x82\xd3\xe4\x93\x02%\x12#/api/v1/workspace/{name=settings/*}\x12\x95\x01\n" +
	"\x13SetWorkspaceSetting\x12\".api.v1.SetWorkspaceSettingRequest\x1a\x12.workspace.Setting\"F\xdaA\asetting\x82\xd3\xe4\x93\x026:\asetting2+/api/v1/workspace/{setting.name=settings/*}\x12\x87\x01\n" +
	"\x15ListIdentityProviders\x12$.api.v1.ListIdentityProvidersRequest\x1a%.api.v1.ListIdentityProvidersResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/identityProviders\x12\x89\x01\n" +
	"\x13GetIdentityProvider\x12\".api.v1.GetIdentityProviderRequest\x1a\x1b.workspace.IdentityProvider\"1\xdaA\x04name\x82\xd3\xe4\x93\x02$\x12\"/api/v1/{name=identityProviders/*}\x12_\n" +
	"\vListInboxes\x12\x1a.api.v1.ListInboxesRequest\x1a\x1b.api.v1.ListInboxesResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/inboxes\x12~\n" +
	"\vUpdateInbox\x12\x1a.api.v1.UpdateInboxRequest\x1a\x10.workspace.Inbox\"A\xdaA\x11inbox,update_mask\x82\xd3\xe4\x93\x02':\x05inbox2\x1e/api/v1/{inbox.name=inboxes/*}\x12j\n" +
	"\vDeleteInbox\x12\x1a.api.v1.DeleteInboxRequest\x1a\x16.google.protobuf.Empty\"'\xdaA\x04name\x82\xd3\xe4\x93\x02\x1a*\x18/api/v1/{name=inboxes/*}B3Z1github.com/smartmemos/memos/internal/proto/api/v1b\x06proto3"

var (
	file_api_v1_workspace_proto_rawDescOnce sync.Once
	file_api_v1_workspace_proto_rawDescData []byte
)

func file_api_v1_workspace_proto_rawDescGZIP() []byte {
	file_api_v1_workspace_proto_rawDescOnce.Do(func() {
		file_api_v1_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_workspace_proto_rawDesc), len(file_api_v1_workspace_proto_rawDesc)))
	})
	return file_api_v1_workspace_proto_rawDescData
}

var file_api_v1_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_v1_workspace_proto_goTypes = []any{
	(*ListIdentityProvidersRequest)(nil),  // 0: api.v1.ListIdentityProvidersRequest
	(*ListIdentityProvidersResponse)(nil), // 1: api.v1.ListIdentityProvidersResponse
	(*GetIdentityProviderRequest)(nil),    // 2: api.v1.GetIdentityProviderRequest
	(*GetWorkspaceProfileRequest)(nil),    // 3: api.v1.GetWorkspaceProfileRequest
	(*GetWorkspaceSettingRequest)(nil),    // 4: api.v1.GetWorkspaceSettingRequest
	(*SetWorkspaceSettingRequest)(nil),    // 5: api.v1.SetWorkspaceSettingRequest
	(*ListInboxesRequest)(nil),            // 6: api.v1.ListInboxesRequest
	(*ListInboxesResponse)(nil),           // 7: api.v1.ListInboxesResponse
	(*UpdateInboxRequest)(nil),            // 8: api.v1.UpdateInboxRequest
	(*DeleteInboxRequest)(nil),            // 9: api.v1.DeleteInboxRequest
	(*workspace.IdentityProvider)(nil),    // 10: workspace.IdentityProvider
	(*workspace.Setting)(nil),             // 11: workspace.Setting
	(*workspace.Inbox)(nil),               // 12: workspace.Inbox
	(*fieldmaskpb.FieldMask)(nil),         // 13: google.protobuf.FieldMask
	(*workspace.Profile)(nil),             // 14: workspace.Profile
	(*emptypb.Empty)(nil),                 // 15: google.protobuf.Empty
}
var file_api_v1_workspace_proto_depIdxs = []int32{
	10, // 0: api.v1.ListIdentityProvidersResponse.identity_providers:type_name -> workspace.IdentityProvider
	11, // 1: api.v1.SetWorkspaceSettingRequest.setting:type_name -> workspace.Setting
	12, // 2: api.v1.ListInboxesResponse.inboxes:type_name -> workspace.Inbox
	12, // 3: api.v1.UpdateInboxRequest.inbox:type_name -> workspace.Inbox
	13, // 4: api.v1.UpdateInboxRequest.update_mask:type_name -> google.protobuf.FieldMask
	3,  // 5: api.v1.WorkspaceService.GetWorkspaceProfile:input_type -> api.v1.GetWorkspaceProfileRequest
	4,  // 6: api.v1.WorkspaceService.GetWorkspaceSetting:input_type -> api.v1.GetWorkspaceSettingRequest
	5,  // 7: api.v1.WorkspaceService.SetWorkspaceSetting:input_type -> api.v1.SetWorkspaceSettingRequest
	0,  // 8: api.v1.WorkspaceService.ListIdentityProviders:input_type -> api.v1.ListIdentityProvidersRequest
	2,  // 9: api.v1.WorkspaceService.GetIdentityProvider:input_type -> api.v1.GetIdentityProviderRequest
	6,  // 10: api.v1.WorkspaceService.ListInboxes:input_type -> api.v1.ListInboxesRequest
	8,  // 11: api.v1.WorkspaceService.UpdateInbox:input_type -> api.v1.UpdateInboxRequest
	9,  // 12: api.v1.WorkspaceService.DeleteInbox:input_type -> api.v1.DeleteInboxRequest
	14, // 13: api.v1.WorkspaceService.GetWorkspaceProfile:output_type -> workspace.Profile
	11, // 14: api.v1.WorkspaceService.GetWorkspaceSetting:output_type -> workspace.Setting
	11, // 15: api.v1.WorkspaceService.SetWorkspaceSetting:output_type -> workspace.Setting
	1,  // 16: api.v1.WorkspaceService.ListIdentityProviders:output_type -> api.v1.ListIdentityProvidersResponse
	10, // 17: api.v1.WorkspaceService.GetIdentityProvider:output_type -> workspace.IdentityProvider
	7,  // 18: api.v1.WorkspaceService.ListInboxes:output_type -> api.v1.ListInboxesResponse
	12, // 19: api.v1.WorkspaceService.UpdateInbox:output_type -> workspace.Inbox
	15, // 20: api.v1.WorkspaceService.DeleteInbox:output_type -> google.protobuf.Empty
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_v1_workspace_proto_init() }
func file_api_v1_workspace_proto_init() {
	if File_api_v1_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_workspace_proto_rawDesc), len(file_api_v1_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_workspace_proto_goTypes,
		DependencyIndexes: file_api_v1_workspace_proto_depIdxs,
		MessageInfos:      file_api_v1_workspace_proto_msgTypes,
	}.Build()
	File_api_v1_workspace_proto = out.File
	file_api_v1_workspace_proto_goTypes = nil
	file_api_v1_workspace_proto_depIdxs = nil
}
