syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "google/api/field_behavior.proto";
import "model/common.proto";

package model;
option go_package = "github.com/smartmemos/memos/internal/proto/model";

message User {
  int64 id = 1;
  string name =2;
  string username = 3;
  enum Role {
    ROLE_UNSPECIFIED = 0;
    HOST = 1;
    ADMIN = 2;
    USER = 3;
  }
  Role role = 4;
  string nickname = 5;
  string email = 6;
  string avatar_url = 7;
  string description = 8;
  string password = 9;
  State state = 10;
  google.protobuf.Timestamp create_at = 11;
  google.protobuf.Timestamp update_at = 12;
}

// User statistics messages
message UserStats {
  // The resource name of the user whose stats these are.
  // Format: users/{user}
  string name = 1;

  // The timestamps when the memos were displayed.
  repeated google.protobuf.Timestamp memo_display_timestamps = 2;

  // The stats of memo types.
  MemoTypeStats memo_type_stats = 3;

  // The count of tags.
  map<string, int32> tag_count = 4;

  // The pinned memos of the user.
  repeated string pinned_memos = 5;

  // Total memo count.
  int32 total_memo_count = 6;

  // Memo type statistics.
  message MemoTypeStats {
    int32 link_count = 1;
    int32 code_count = 2;
    int32 todo_count = 3;
    int32 undo_count = 4;
  }
}

