// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file model/common.proto (package model, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/common.proto.
 */
export const file_model_common: GenFile = /*@__PURE__*/
  fileDesc("ChJtb2RlbC9jb21tb24ucHJvdG8SBW1vZGVsIioKCVBhZ2VUb2tlbhINCgVsaW1pdBgBIAEoBRIOCgZvZmZzZXQYAiABKAUiRAoITG9jYXRpb24SEwoLcGxhY2Vob2xkZXIYASABKAkSEAoIbGF0aXR1ZGUYAiABKAESEQoJbG9uZ2l0dWRlGAMgASgBKjgKBVN0YXRlEhUKEVNUQVRFX1VOU1BFQ0lGSUVEEAASCgoGTk9STUFMEAESDAoIQVJDSElWRUQQAio5CglEaXJlY3Rpb24SGQoVRElSRUNUSU9OX1VOU1BFQ0lGSUVEEAASBwoDQVNDEAESCAoEREVTQxACKlAKClZpc2liaWxpdHkSGgoWVklTSUJJTElUWV9VTlNQRUNJRklFRBAAEgsKB1BSSVZBVEUQARINCglQUk9URUNURUQQAhIKCgZQVUJMSUMQA0IyWjBnaXRodWIuY29tL3NtYXJ0bWVtb3MvbWVtb3MvaW50ZXJuYWwvcHJvdG8vbW9kZWxiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * Used internally for obfuscating the page token.
 *
 * @generated from message model.PageToken
 */
export type PageToken = Message<"model.PageToken"> & {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * @generated from field: int32 offset = 2;
   */
  offset: number;
};

/**
 * Describes the message model.PageToken.
 * Use `create(PageTokenSchema)` to create a new message.
 */
export const PageTokenSchema: GenMessage<PageToken> = /*@__PURE__*/
  messageDesc(file_model_common, 0);

/**
 * @generated from message model.Location
 */
export type Location = Message<"model.Location"> & {
  /**
   * A placeholder text for the location.
   *
   * @generated from field: string placeholder = 1;
   */
  placeholder: string;

  /**
   * The latitude of the location.
   *
   * @generated from field: double latitude = 2;
   */
  latitude: number;

  /**
   * The longitude of the location.
   *
   * @generated from field: double longitude = 3;
   */
  longitude: number;
};

/**
 * Describes the message model.Location.
 * Use `create(LocationSchema)` to create a new message.
 */
export const LocationSchema: GenMessage<Location> = /*@__PURE__*/
  messageDesc(file_model_common, 1);

/**
 * @generated from enum model.State
 */
export enum State {
  /**
   * @generated from enum value: STATE_UNSPECIFIED = 0;
   */
  STATE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: NORMAL = 1;
   */
  NORMAL = 1,

  /**
   * @generated from enum value: ARCHIVED = 2;
   */
  ARCHIVED = 2,
}

/**
 * Describes the enum model.State.
 */
export const StateSchema: GenEnum<State> = /*@__PURE__*/
  enumDesc(file_model_common, 0);

/**
 * @generated from enum model.Direction
 */
export enum Direction {
  /**
   * @generated from enum value: DIRECTION_UNSPECIFIED = 0;
   */
  DIRECTION_UNSPECIFIED = 0,

  /**
   * @generated from enum value: ASC = 1;
   */
  ASC = 1,

  /**
   * @generated from enum value: DESC = 2;
   */
  DESC = 2,
}

/**
 * Describes the enum model.Direction.
 */
export const DirectionSchema: GenEnum<Direction> = /*@__PURE__*/
  enumDesc(file_model_common, 1);

/**
 * @generated from enum model.Visibility
 */
export enum Visibility {
  /**
   * @generated from enum value: VISIBILITY_UNSPECIFIED = 0;
   */
  VISIBILITY_UNSPECIFIED = 0,

  /**
   * @generated from enum value: PRIVATE = 1;
   */
  PRIVATE = 1,

  /**
   * @generated from enum value: PROTECTED = 2;
   */
  PROTECTED = 2,

  /**
   * @generated from enum value: PUBLIC = 3;
   */
  PUBLIC = 3,
}

/**
 * Describes the enum model.Visibility.
 */
export const VisibilitySchema: GenEnum<Visibility> = /*@__PURE__*/
  enumDesc(file_model_common, 2);

