// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file model/memo.proto (package model, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_api_field_behavior } from "../google/api/field_behavior_pb";
import type { State } from "./common_pb";
import { file_model_common } from "./common_pb";
import type { Node } from "./markdown_pb";
import { file_model_markdown } from "./markdown_pb";
import type { Reaction } from "./reaction_pb";
import { file_model_reaction } from "./reaction_pb";
import type { MemoRelation } from "./memo_relation_pb";
import { file_model_memo_relation } from "./memo_relation_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/memo.proto.
 */
export const file_model_memo: GenFile = /*@__PURE__*/
  fileDesc("ChBtb2RlbC9tZW1vLnByb3RvEgVtb2RlbCKvBQoETWVtbxIMCgRuYW1lGAEgASgJEhsKBXN0YXRlGAIgASgOMgwubW9kZWwuU3RhdGUSDwoHY3JlYXRvchgDIAEoCRIvCgtjcmVhdGVfdGltZRgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLwoLdXBkYXRlX3RpbWUYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEjAKDGRpc3BsYXlfdGltZRgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDwoHY29udGVudBgHIAEoCRIaCgVub2RlcxgIIAMoCzILLm1vZGVsLk5vZGUSJQoKdmlzaWJpbGl0eRgJIAEoDjIRLm1vZGVsLlZpc2liaWxpdHkSDAoEdGFncxgKIAMoCRIOCgZwaW5uZWQYCyABKAgSJgoLYXR0YWNobWVudHMYDCADKAsyES5tb2RlbC5BdHRhY2htZW50EiYKCXJlbGF0aW9ucxgNIAMoCzITLm1vZGVsLk1lbW9SZWxhdGlvbhIiCglyZWFjdGlvbnMYDiADKAsyDy5tb2RlbC5SZWFjdGlvbhImCghwcm9wZXJ0eRgPIAEoCzIULm1vZGVsLk1lbW8uUHJvcGVydHkSEwoGcGFyZW50GBAgASgJSACIAQESDwoHc25pcHBldBgRIAEoCRImCghsb2NhdGlvbhgSIAEoCzIPLm1vZGVsLkxvY2F0aW9uSAGIAQEaYwoIUHJvcGVydHkSEAoIaGFzX2xpbmsYASABKAgSFQoNaGFzX3Rhc2tfbGlzdBgCIAEoCBIQCghoYXNfY29kZRgDIAEoCBIcChRoYXNfaW5jb21wbGV0ZV90YXNrcxgEIAEoCEIJCgdfcGFyZW50QgsKCV9sb2NhdGlvbiK9AQoKQXR0YWNobWVudBIMCgRuYW1lGAEgASgJEi8KC2NyZWF0ZV90aW1lGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIQCghmaWxlbmFtZRgDIAEoCRIPCgdjb250ZW50GAQgASgMEhUKDWV4dGVybmFsX2xpbmsYBSABKAkSDAoEdHlwZRgGIAEoCRIMCgRzaXplGAcgASgDEhEKBG1lbW8YCCABKAlIAIgBAUIHCgVfbWVtbyJECghMb2NhdGlvbhITCgtwbGFjZWhvbGRlchgBIAEoCRIQCghsYXRpdHVkZRgCIAEoARIRCglsb25naXR1ZGUYAyABKAEqUAoKVmlzaWJpbGl0eRIaChZWSVNJQklMSVRZX1VOU1BFQ0lGSUVEEAASCwoHUFJJVkFURRABEg0KCVBST1RFQ1RFRBACEgoKBlBVQkxJQxADQjJaMGdpdGh1Yi5jb20vc21hcnRtZW1vcy9tZW1vcy9pbnRlcm5hbC9wcm90by9tb2RlbGIGcHJvdG8z", [file_google_protobuf_timestamp, file_google_api_field_behavior, file_model_common, file_model_markdown, file_model_reaction, file_model_memo_relation]);

/**
 * @generated from message model.Memo
 */
export type Memo = Message<"model.Memo"> & {
  /**
   * The resource name of the memo.
   * Format: memos/{memo}, memo is the user defined id or uuid.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The state of the memo.
   *
   * @generated from field: model.State state = 2;
   */
  state: State;

  /**
   * The name of the creator.
   * Format: users/{user}
   *
   * @generated from field: string creator = 3;
   */
  creator: string;

  /**
   * Output only. The creation timestamp.
   *
   * @generated from field: google.protobuf.Timestamp create_time = 4;
   */
  createTime?: Timestamp;

  /**
   * Output only. The last update timestamp.
   *
   * @generated from field: google.protobuf.Timestamp update_time = 5;
   */
  updateTime?: Timestamp;

  /**
   * The display timestamp of the memo.
   *
   * @generated from field: google.protobuf.Timestamp display_time = 6;
   */
  displayTime?: Timestamp;

  /**
   * Required. The content of the memo in Markdown format.
   *
   * @generated from field: string content = 7;
   */
  content: string;

  /**
   * Output only. The parsed nodes from the content.
   *
   * @generated from field: repeated model.Node nodes = 8;
   */
  nodes: Node[];

  /**
   * The visibility of the memo.
   *
   * @generated from field: model.Visibility visibility = 9;
   */
  visibility: Visibility;

  /**
   * Output only. The tags extracted from the content.
   *
   * @generated from field: repeated string tags = 10;
   */
  tags: string[];

  /**
   * Whether the memo is pinned.
   *
   * @generated from field: bool pinned = 11;
   */
  pinned: boolean;

  /**
   * Optional. The attachments of the memo.
   *
   * @generated from field: repeated model.Attachment attachments = 12;
   */
  attachments: Attachment[];

  /**
   * Optional. The relations of the memo.
   *
   * @generated from field: repeated model.MemoRelation relations = 13;
   */
  relations: MemoRelation[];

  /**
   * Output only. The reactions to the memo.
   *
   * @generated from field: repeated model.Reaction reactions = 14;
   */
  reactions: Reaction[];

  /**
   * Output only. The computed properties of the memo.
   *
   * @generated from field: model.Memo.Property property = 15;
   */
  property?: Memo_Property;

  /**
   * Output only. The name of the parent memo.
   * Format: memos/{memo}
   *
   * @generated from field: optional string parent = 16;
   */
  parent?: string;

  /**
   * Output only. The snippet of the memo content. Plain text only.
   *
   * @generated from field: string snippet = 17;
   */
  snippet: string;

  /**
   * Optional. The location of the memo.
   *
   * @generated from field: optional model.Location location = 18;
   */
  location?: Location;
};

/**
 * Describes the message model.Memo.
 * Use `create(MemoSchema)` to create a new message.
 */
export const MemoSchema: GenMessage<Memo> = /*@__PURE__*/
  messageDesc(file_model_memo, 0);

/**
 * Computed properties of a memo.
 *
 * @generated from message model.Memo.Property
 */
export type Memo_Property = Message<"model.Memo.Property"> & {
  /**
   * @generated from field: bool has_link = 1;
   */
  hasLink: boolean;

  /**
   * @generated from field: bool has_task_list = 2;
   */
  hasTaskList: boolean;

  /**
   * @generated from field: bool has_code = 3;
   */
  hasCode: boolean;

  /**
   * @generated from field: bool has_incomplete_tasks = 4;
   */
  hasIncompleteTasks: boolean;
};

/**
 * Describes the message model.Memo.Property.
 * Use `create(Memo_PropertySchema)` to create a new message.
 */
export const Memo_PropertySchema: GenMessage<Memo_Property> = /*@__PURE__*/
  messageDesc(file_model_memo, 0, 0);

/**
 * @generated from message model.Attachment
 */
export type Attachment = Message<"model.Attachment"> & {
  /**
   * The name of the attachment.
   * Format: attachments/{attachment}
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Output only. The creation timestamp.
   *
   * @generated from field: google.protobuf.Timestamp create_time = 2;
   */
  createTime?: Timestamp;

  /**
   * The filename of the attachment.
   *
   * @generated from field: string filename = 3;
   */
  filename: string;

  /**
   * Input only. The content of the attachment.
   *
   * @generated from field: bytes content = 4;
   */
  content: Uint8Array;

  /**
   * Optional. The external link of the attachment.
   *
   * @generated from field: string external_link = 5;
   */
  externalLink: string;

  /**
   * The MIME type of the attachment.
   *
   * @generated from field: string type = 6;
   */
  type: string;

  /**
   * Output only. The size of the attachment in bytes.
   *
   * @generated from field: int64 size = 7;
   */
  size: bigint;

  /**
   * Optional. The related memo. Refer to `Memo.name`.
   * Format: memos/{memo}
   *
   * @generated from field: optional string memo = 8;
   */
  memo?: string;
};

/**
 * Describes the message model.Attachment.
 * Use `create(AttachmentSchema)` to create a new message.
 */
export const AttachmentSchema: GenMessage<Attachment> = /*@__PURE__*/
  messageDesc(file_model_memo, 1);

/**
 * @generated from message model.Location
 */
export type Location = Message<"model.Location"> & {
  /**
   * A placeholder text for the location.
   *
   * @generated from field: string placeholder = 1;
   */
  placeholder: string;

  /**
   * The latitude of the location.
   *
   * @generated from field: double latitude = 2;
   */
  latitude: number;

  /**
   * The longitude of the location.
   *
   * @generated from field: double longitude = 3;
   */
  longitude: number;
};

/**
 * Describes the message model.Location.
 * Use `create(LocationSchema)` to create a new message.
 */
export const LocationSchema: GenMessage<Location> = /*@__PURE__*/
  messageDesc(file_model_memo, 2);

/**
 * @generated from enum model.Visibility
 */
export enum Visibility {
  /**
   * @generated from enum value: VISIBILITY_UNSPECIFIED = 0;
   */
  VISIBILITY_UNSPECIFIED = 0,

  /**
   * @generated from enum value: PRIVATE = 1;
   */
  PRIVATE = 1,

  /**
   * @generated from enum value: PROTECTED = 2;
   */
  PROTECTED = 2,

  /**
   * @generated from enum value: PUBLIC = 3;
   */
  PUBLIC = 3,
}

/**
 * Describes the enum model.Visibility.
 */
export const VisibilitySchema: GenEnum<Visibility> = /*@__PURE__*/
  enumDesc(file_model_memo, 0);

