// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file model/user.proto (package model, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_api_field_behavior } from "../google/api/field_behavior_pb";
import { file_model_common_common } from "./common/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/user.proto.
 */
export const file_model_user: GenFile = /*@__PURE__*/
  fileDesc("ChBtb2RlbC91c2VyLnByb3RvEgVtb2RlbCLmAgoEVXNlchIKCgJpZBgBIAEoAxIMCgRuYW1lGAIgASgJEhAKCHVzZXJuYW1lGAMgASgJEh4KBHJvbGUYBCABKA4yEC5tb2RlbC5Vc2VyLlJvbGUSEAoIbmlja25hbWUYBSABKAkSDQoFZW1haWwYBiABKAkSEgoKYXZhdGFyX3VybBgHIAEoCRITCgtkZXNjcmlwdGlvbhgIIAEoCRIQCghwYXNzd29yZBgJIAEoCRIbCgVzdGF0ZRgKIAEoDjIMLm1vZGVsLlN0YXRlEi0KCWNyZWF0ZV9hdBgLIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLQoJdXBkYXRlX2F0GAwgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCI7CgRSb2xlEhQKEFJPTEVfVU5TUEVDSUZJRUQQABIICgRIT1NUEAESCQoFQURNSU4QAhIICgRVU0VSEAMiKgoJUGFnZVRva2VuEg0KBWxpbWl0GAEgASgFEg4KBm9mZnNldBgCIAEoBSo4CgVTdGF0ZRIVChFTVEFURV9VTlNQRUNJRklFRBAAEgoKBk5PUk1BTBABEgwKCEFSQ0hJVkVEEAIqOQoJRGlyZWN0aW9uEhkKFURJUkVDVElPTl9VTlNQRUNJRklFRBAAEgcKA0FTQxABEggKBERFU0MQAkI3WjVnaXRodWIuY29tL3NtYXJ0bWVtb3MvbWVtb3MvaW50ZXJuYWwvcHJvdG8vbW9kZWwvdXNlcmIGcHJvdG8z", [file_google_protobuf_timestamp, file_google_api_field_behavior, file_model_common_common]);

/**
 * @generated from message model.User
 */
export type User = Message<"model.User"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: model.User.Role role = 4;
   */
  role: User_Role;

  /**
   * @generated from field: string nickname = 5;
   */
  nickname: string;

  /**
   * @generated from field: string email = 6;
   */
  email: string;

  /**
   * @generated from field: string avatar_url = 7;
   */
  avatarUrl: string;

  /**
   * @generated from field: string description = 8;
   */
  description: string;

  /**
   * @generated from field: string password = 9;
   */
  password: string;

  /**
   * @generated from field: model.State state = 10;
   */
  state: State;

  /**
   * @generated from field: google.protobuf.Timestamp create_at = 11;
   */
  createAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp update_at = 12;
   */
  updateAt?: Timestamp;
};

/**
 * Describes the message model.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_model_user, 0);

/**
 * @generated from enum model.User.Role
 */
export enum User_Role {
  /**
   * @generated from enum value: ROLE_UNSPECIFIED = 0;
   */
  ROLE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: HOST = 1;
   */
  HOST = 1,

  /**
   * @generated from enum value: ADMIN = 2;
   */
  ADMIN = 2,

  /**
   * @generated from enum value: USER = 3;
   */
  USER = 3,
}

/**
 * Describes the enum model.User.Role.
 */
export const User_RoleSchema: GenEnum<User_Role> = /*@__PURE__*/
  enumDesc(file_model_user, 0, 0);

/**
 * Used internally for obfuscating the page token.
 *
 * @generated from message model.PageToken
 */
export type PageToken = Message<"model.PageToken"> & {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  /**
   * @generated from field: int32 offset = 2;
   */
  offset: number;
};

/**
 * Describes the message model.PageToken.
 * Use `create(PageTokenSchema)` to create a new message.
 */
export const PageTokenSchema: GenMessage<PageToken> = /*@__PURE__*/
  messageDesc(file_model_user, 1);

/**
 * @generated from enum model.State
 */
export enum State {
  /**
   * @generated from enum value: STATE_UNSPECIFIED = 0;
   */
  STATE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: NORMAL = 1;
   */
  NORMAL = 1,

  /**
   * @generated from enum value: ARCHIVED = 2;
   */
  ARCHIVED = 2,
}

/**
 * Describes the enum model.State.
 */
export const StateSchema: GenEnum<State> = /*@__PURE__*/
  enumDesc(file_model_user, 0);

/**
 * @generated from enum model.Direction
 */
export enum Direction {
  /**
   * @generated from enum value: DIRECTION_UNSPECIFIED = 0;
   */
  DIRECTION_UNSPECIFIED = 0,

  /**
   * @generated from enum value: ASC = 1;
   */
  ASC = 1,

  /**
   * @generated from enum value: DESC = 2;
   */
  DESC = 2,
}

/**
 * Describes the enum model.Direction.
 */
export const DirectionSchema: GenEnum<Direction> = /*@__PURE__*/
  enumDesc(file_model_user, 1);

