// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: model/workspace/inbox.proto

package workspace

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Inbox_Status int32

const (
	Inbox_STATUS_UNSPECIFIED Inbox_Status = 0
	Inbox_UNREAD             Inbox_Status = 1
	Inbox_ARCHIVED           Inbox_Status = 2
)

// Enum value maps for Inbox_Status.
var (
	Inbox_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "UNREAD",
		2: "ARCHIVED",
	}
	Inbox_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"UNREAD":             1,
		"ARCHIVED":           2,
	}
)

func (x Inbox_Status) Enum() *Inbox_Status {
	p := new(Inbox_Status)
	*p = x
	return p
}

func (x Inbox_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Inbox_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_model_workspace_inbox_proto_enumTypes[0].Descriptor()
}

func (Inbox_Status) Type() protoreflect.EnumType {
	return &file_model_workspace_inbox_proto_enumTypes[0]
}

func (x Inbox_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Inbox_Status.Descriptor instead.
func (Inbox_Status) EnumDescriptor() ([]byte, []int) {
	return file_model_workspace_inbox_proto_rawDescGZIP(), []int{0, 0}
}

type Inbox_Type int32

const (
	Inbox_TYPE_UNSPECIFIED Inbox_Type = 0
	Inbox_MEMO_COMMENT     Inbox_Type = 1
	Inbox_VERSION_UPDATE   Inbox_Type = 2
)

// Enum value maps for Inbox_Type.
var (
	Inbox_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "MEMO_COMMENT",
		2: "VERSION_UPDATE",
	}
	Inbox_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"MEMO_COMMENT":     1,
		"VERSION_UPDATE":   2,
	}
)

func (x Inbox_Type) Enum() *Inbox_Type {
	p := new(Inbox_Type)
	*p = x
	return p
}

func (x Inbox_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Inbox_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_model_workspace_inbox_proto_enumTypes[1].Descriptor()
}

func (Inbox_Type) Type() protoreflect.EnumType {
	return &file_model_workspace_inbox_proto_enumTypes[1]
}

func (x Inbox_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Inbox_Type.Descriptor instead.
func (Inbox_Type) EnumDescriptor() ([]byte, []int) {
	return file_model_workspace_inbox_proto_rawDescGZIP(), []int{0, 1}
}

type Inbox struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the inbox.
	// Format: inboxes/{id}, id is the system generated auto-incremented id.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Format: users/{user}
	Sender string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Format: users/{user}
	Receiver      string                 `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Status        Inbox_Status           `protobuf:"varint,4,opt,name=status,proto3,enum=workspace.Inbox_Status" json:"status,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Type          Inbox_Type             `protobuf:"varint,6,opt,name=type,proto3,enum=workspace.Inbox_Type" json:"type,omitempty"`
	ActivityId    *int32                 `protobuf:"varint,7,opt,name=activity_id,json=activityId,proto3,oneof" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inbox) Reset() {
	*x = Inbox{}
	mi := &file_model_workspace_inbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inbox) ProtoMessage() {}

func (x *Inbox) ProtoReflect() protoreflect.Message {
	mi := &file_model_workspace_inbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inbox.ProtoReflect.Descriptor instead.
func (*Inbox) Descriptor() ([]byte, []int) {
	return file_model_workspace_inbox_proto_rawDescGZIP(), []int{0}
}

func (x *Inbox) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Inbox) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Inbox) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Inbox) GetStatus() Inbox_Status {
	if x != nil {
		return x.Status
	}
	return Inbox_STATUS_UNSPECIFIED
}

func (x *Inbox) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Inbox) GetType() Inbox_Type {
	if x != nil {
		return x.Type
	}
	return Inbox_TYPE_UNSPECIFIED
}

func (x *Inbox) GetActivityId() int32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

var File_model_workspace_inbox_proto protoreflect.FileDescriptor

var file_model_workspace_inbox_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x2f, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x03, 0x0a, 0x05, 0x49, 0x6e,
	0x62, 0x6f, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3b, 0x0a, 0x0b,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x88, 0x01, 0x01, 0x22, 0x3a, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x55, 0x4e, 0x52, 0x45, 0x41, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x52, 0x43, 0x48,
	0x49, 0x56, 0x45, 0x44, 0x10, 0x02, 0x22, 0x42, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x45, 0x4d, 0x4f, 0x5f, 0x43, 0x4f, 0x4d,
	0x4d, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f,
	0x4e, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x02, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x6d, 0x65,
	0x6d, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x6d, 0x6f, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_model_workspace_inbox_proto_rawDescOnce sync.Once
	file_model_workspace_inbox_proto_rawDescData []byte
)

func file_model_workspace_inbox_proto_rawDescGZIP() []byte {
	file_model_workspace_inbox_proto_rawDescOnce.Do(func() {
		file_model_workspace_inbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_workspace_inbox_proto_rawDesc), len(file_model_workspace_inbox_proto_rawDesc)))
	})
	return file_model_workspace_inbox_proto_rawDescData
}

var file_model_workspace_inbox_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_model_workspace_inbox_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_workspace_inbox_proto_goTypes = []any{
	(Inbox_Status)(0),             // 0: workspace.Inbox.Status
	(Inbox_Type)(0),               // 1: workspace.Inbox.Type
	(*Inbox)(nil),                 // 2: workspace.Inbox
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_model_workspace_inbox_proto_depIdxs = []int32{
	0, // 0: workspace.Inbox.status:type_name -> workspace.Inbox.Status
	3, // 1: workspace.Inbox.create_time:type_name -> google.protobuf.Timestamp
	1, // 2: workspace.Inbox.type:type_name -> workspace.Inbox.Type
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_workspace_inbox_proto_init() }
func file_model_workspace_inbox_proto_init() {
	if File_model_workspace_inbox_proto != nil {
		return
	}
	file_model_workspace_inbox_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_workspace_inbox_proto_rawDesc), len(file_model_workspace_inbox_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_workspace_inbox_proto_goTypes,
		DependencyIndexes: file_model_workspace_inbox_proto_depIdxs,
		EnumInfos:         file_model_workspace_inbox_proto_enumTypes,
		MessageInfos:      file_model_workspace_inbox_proto_msgTypes,
	}.Build()
	File_model_workspace_inbox_proto = out.File
	file_model_workspace_inbox_proto_goTypes = nil
	file_model_workspace_inbox_proto_depIdxs = nil
}
