// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: model/memo_relation.proto

package model

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The type of the relation.
type MemoRelation_Type int32

const (
	MemoRelation_TYPE_UNSPECIFIED MemoRelation_Type = 0
	MemoRelation_REFERENCE        MemoRelation_Type = 1
	MemoRelation_COMMENT          MemoRelation_Type = 2
)

// Enum value maps for MemoRelation_Type.
var (
	MemoRelation_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "REFERENCE",
		2: "COMMENT",
	}
	MemoRelation_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"REFERENCE":        1,
		"COMMENT":          2,
	}
)

func (x MemoRelation_Type) Enum() *MemoRelation_Type {
	p := new(MemoRelation_Type)
	*p = x
	return p
}

func (x MemoRelation_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemoRelation_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_model_memo_relation_proto_enumTypes[0].Descriptor()
}

func (MemoRelation_Type) Type() protoreflect.EnumType {
	return &file_model_memo_relation_proto_enumTypes[0]
}

func (x MemoRelation_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemoRelation_Type.Descriptor instead.
func (MemoRelation_Type) EnumDescriptor() ([]byte, []int) {
	return file_model_memo_relation_proto_rawDescGZIP(), []int{0, 0}
}

type MemoRelation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The memo in the relation.
	Memo *MemoRelation_Memo `protobuf:"bytes,1,opt,name=memo,proto3" json:"memo,omitempty"`
	// The related memo.
	RelatedMemo   *MemoRelation_Memo `protobuf:"bytes,2,opt,name=related_memo,json=relatedMemo,proto3" json:"related_memo,omitempty"`
	Type          MemoRelation_Type  `protobuf:"varint,3,opt,name=type,proto3,enum=model.MemoRelation_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoRelation) Reset() {
	*x = MemoRelation{}
	mi := &file_model_memo_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoRelation) ProtoMessage() {}

func (x *MemoRelation) ProtoReflect() protoreflect.Message {
	mi := &file_model_memo_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoRelation.ProtoReflect.Descriptor instead.
func (*MemoRelation) Descriptor() ([]byte, []int) {
	return file_model_memo_relation_proto_rawDescGZIP(), []int{0}
}

func (x *MemoRelation) GetMemo() *MemoRelation_Memo {
	if x != nil {
		return x.Memo
	}
	return nil
}

func (x *MemoRelation) GetRelatedMemo() *MemoRelation_Memo {
	if x != nil {
		return x.RelatedMemo
	}
	return nil
}

func (x *MemoRelation) GetType() MemoRelation_Type {
	if x != nil {
		return x.Type
	}
	return MemoRelation_TYPE_UNSPECIFIED
}

// Memo reference in relations.
type MemoRelation_Memo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the memo.
	// Format: memos/{memo}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Output only. The snippet of the memo content. Plain text only.
	Snippet       string `protobuf:"bytes,2,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoRelation_Memo) Reset() {
	*x = MemoRelation_Memo{}
	mi := &file_model_memo_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoRelation_Memo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoRelation_Memo) ProtoMessage() {}

func (x *MemoRelation_Memo) ProtoReflect() protoreflect.Message {
	mi := &file_model_memo_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoRelation_Memo.ProtoReflect.Descriptor instead.
func (*MemoRelation_Memo) Descriptor() ([]byte, []int) {
	return file_model_memo_relation_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MemoRelation_Memo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemoRelation_Memo) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

var File_model_memo_relation_proto protoreflect.FileDescriptor

const file_model_memo_relation_proto_rawDesc = "" +
	"\n" +
	"\x19model/memo_relation.proto\x12\x05model\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x12model/common.proto\x1a\x14model/markdown.proto\x1a\x14model/reaction.proto\"\x97\x02\n" +
	"\fMemoRelation\x12,\n" +
	"\x04memo\x18\x01 \x01(\v2\x18.model.MemoRelation.MemoR\x04memo\x12;\n" +
	"\frelated_memo\x18\x02 \x01(\v2\x18.model.MemoRelation.MemoR\vrelatedMemo\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.model.MemoRelation.TypeR\x04type\x1a4\n" +
	"\x04Memo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asnippet\x18\x02 \x01(\tR\asnippet\"8\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tREFERENCE\x10\x01\x12\v\n" +
	"\aCOMMENT\x10\x02B2Z0github.com/smartmemos/memos/internal/proto/modelb\x06proto3"

var (
	file_model_memo_relation_proto_rawDescOnce sync.Once
	file_model_memo_relation_proto_rawDescData []byte
)

func file_model_memo_relation_proto_rawDescGZIP() []byte {
	file_model_memo_relation_proto_rawDescOnce.Do(func() {
		file_model_memo_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_memo_relation_proto_rawDesc), len(file_model_memo_relation_proto_rawDesc)))
	})
	return file_model_memo_relation_proto_rawDescData
}

var file_model_memo_relation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_model_memo_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_memo_relation_proto_goTypes = []any{
	(MemoRelation_Type)(0),    // 0: model.MemoRelation.Type
	(*MemoRelation)(nil),      // 1: model.MemoRelation
	(*MemoRelation_Memo)(nil), // 2: model.MemoRelation.Memo
}
var file_model_memo_relation_proto_depIdxs = []int32{
	2, // 0: model.MemoRelation.memo:type_name -> model.MemoRelation.Memo
	2, // 1: model.MemoRelation.related_memo:type_name -> model.MemoRelation.Memo
	0, // 2: model.MemoRelation.type:type_name -> model.MemoRelation.Type
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_memo_relation_proto_init() }
func file_model_memo_relation_proto_init() {
	if File_model_memo_relation_proto != nil {
		return
	}
	file_model_common_proto_init()
	file_model_markdown_proto_init()
	file_model_reaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_memo_relation_proto_rawDesc), len(file_model_memo_relation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_memo_relation_proto_goTypes,
		DependencyIndexes: file_model_memo_relation_proto_depIdxs,
		EnumInfos:         file_model_memo_relation_proto_enumTypes,
		MessageInfos:      file_model_memo_relation_proto_msgTypes,
	}.Build()
	File_model_memo_relation_proto = out.File
	file_model_memo_relation_proto_goTypes = nil
	file_model_memo_relation_proto_depIdxs = nil
}
