// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: model/reaction.proto

package model

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the reaction.
	// Format: reactions/{reaction}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The resource name of the creator.
	// Format: users/{user}
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	// The resource name of the content.
	// For memo reactions, this should be the memo's resource name.
	// Format: memos/{memo}
	ContentId string `protobuf:"bytes,3,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	// Required. The type of reaction (e.g., "👍", "❤️", "😄").
	ReactionType string `protobuf:"bytes,4,opt,name=reaction_type,json=reactionType,proto3" json:"reaction_type,omitempty"`
	// Output only. The creation timestamp.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reaction) Reset() {
	*x = Reaction{}
	mi := &file_model_reaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reaction) ProtoMessage() {}

func (x *Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_model_reaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reaction.ProtoReflect.Descriptor instead.
func (*Reaction) Descriptor() ([]byte, []int) {
	return file_model_reaction_proto_rawDescGZIP(), []int{0}
}

func (x *Reaction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Reaction) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Reaction) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *Reaction) GetReactionType() string {
	if x != nil {
		return x.ReactionType
	}
	return ""
}

func (x *Reaction) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

var File_model_reaction_proto protoreflect.FileDescriptor

const file_model_reaction_proto_rawDesc = "" +
	"\n" +
	"\x14model/reaction.proto\x12\x05model\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x12model/common.proto\x1a\x14model/markdown.proto\"\xb9\x01\n" +
	"\bReaction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acreator\x18\x02 \x01(\tR\acreator\x12\x1d\n" +
	"\n" +
	"content_id\x18\x03 \x01(\tR\tcontentId\x12#\n" +
	"\rreaction_type\x18\x04 \x01(\tR\freactionType\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTimeB2Z0github.com/smartmemos/memos/internal/proto/modelb\x06proto3"

var (
	file_model_reaction_proto_rawDescOnce sync.Once
	file_model_reaction_proto_rawDescData []byte
)

func file_model_reaction_proto_rawDescGZIP() []byte {
	file_model_reaction_proto_rawDescOnce.Do(func() {
		file_model_reaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_reaction_proto_rawDesc), len(file_model_reaction_proto_rawDesc)))
	})
	return file_model_reaction_proto_rawDescData
}

var file_model_reaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_reaction_proto_goTypes = []any{
	(*Reaction)(nil),              // 0: model.Reaction
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_model_reaction_proto_depIdxs = []int32{
	1, // 0: model.Reaction.create_time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_reaction_proto_init() }
func file_model_reaction_proto_init() {
	if File_model_reaction_proto != nil {
		return
	}
	file_model_common_proto_init()
	file_model_markdown_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_reaction_proto_rawDesc), len(file_model_reaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_reaction_proto_goTypes,
		DependencyIndexes: file_model_reaction_proto_depIdxs,
		MessageInfos:      file_model_reaction_proto_msgTypes,
	}.Build()
	File_model_reaction_proto = out.File
	file_model_reaction_proto_goTypes = nil
	file_model_reaction_proto_depIdxs = nil
}
