// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file api/v2/user.proto (package api.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_client } from "../../google/api/client_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { User, UserSchema } from "../../model/user_pb";
import { file_model_user } from "../../model/user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v2/user.proto.
 */
export const file_api_v2_user: GenFile = /*@__PURE__*/
  fileDesc("ChFhcGkvdjIvdXNlci5wcm90bxIGYXBpLnYyIi4KEUNyZWF0ZVVzZXJSZXF1ZXN0EhkKBHVzZXIYASABKAsyCy5tb2RlbC5Vc2VyMkUKC1VzZXJTZXJ2aWNlEjYKCkNyZWF0ZVVzZXISGS5hcGkudjIuQ3JlYXRlVXNlclJlcXVlc3QaCy5tb2RlbC5Vc2VyIgBCM1oxZ2l0aHViLmNvbS9zbWFydG1lbW9zL21lbW9zL2ludGVybmFsL3Byb3RvL2FwaS92MmIGcHJvdG8z", [file_google_api_annotations, file_google_api_client, file_google_api_field_behavior, file_google_protobuf_empty, file_google_protobuf_timestamp, file_model_user]);

/**
 * @generated from message api.v2.CreateUserRequest
 */
export type CreateUserRequest = Message<"api.v2.CreateUserRequest"> & {
  /**
   * Required. The user to create.
   *
   * @generated from field: model.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message api.v2.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema: GenMessage<CreateUserRequest> = /*@__PURE__*/
  messageDesc(file_api_v2_user, 0);

/**
 * @generated from service api.v2.UserService
 */
export const UserService: GenService<{
  /**
   * CreateUser creates a new user.
   *
   * @generated from rpc api.v2.UserService.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof CreateUserRequestSchema;
    output: typeof UserSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v2_user, 0);

