// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file api/v2/workspace.proto (package api.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_model_user } from "../../model/user_pb";
import type { WorkspaceProfileSchema } from "../../model/workspace_pb";
import { file_model_workspace } from "../../model/workspace_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v2/workspace.proto.
 */
export const file_api_v2_workspace: GenFile = /*@__PURE__*/
  fileDesc("ChZhcGkvdjIvd29ya3NwYWNlLnByb3RvEgZhcGkudjIiHAoaR2V0V29ya3NwYWNlUHJvZmlsZVJlcXVlc3QyaAoQV29ya3NwYWNlU2VydmljZRJUChNHZXRXb3Jrc3BhY2VQcm9maWxlEiIuYXBpLnYyLkdldFdvcmtzcGFjZVByb2ZpbGVSZXF1ZXN0GhcubW9kZWwuV29ya3NwYWNlUHJvZmlsZSIAQjNaMWdpdGh1Yi5jb20vc21hcnRtZW1vcy9tZW1vcy9pbnRlcm5hbC9wcm90by9hcGkvdjJiBnByb3RvMw", [file_google_protobuf_empty, file_google_protobuf_timestamp, file_model_user, file_model_workspace]);

/**
 * Request for workspace profile.
 *
 * @generated from message api.v2.GetWorkspaceProfileRequest
 */
export type GetWorkspaceProfileRequest = Message<"api.v2.GetWorkspaceProfileRequest"> & {
};

/**
 * Describes the message api.v2.GetWorkspaceProfileRequest.
 * Use `create(GetWorkspaceProfileRequestSchema)` to create a new message.
 */
export const GetWorkspaceProfileRequestSchema: GenMessage<GetWorkspaceProfileRequest> = /*@__PURE__*/
  messageDesc(file_api_v2_workspace, 0);

/**
 * @generated from service api.v2.WorkspaceService
 */
export const WorkspaceService: GenService<{
  /**
   * Gets the workspace profile.
   *
   * @generated from rpc api.v2.WorkspaceService.GetWorkspaceProfile
   */
  getWorkspaceProfile: {
    methodKind: "unary";
    input: typeof GetWorkspaceProfileRequestSchema;
    output: typeof WorkspaceProfileSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v2_workspace, 0);

