// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file model/workspace/inbox.proto (package workspace, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/workspace/inbox.proto.
 */
export const file_model_workspace_inbox: GenFile = /*@__PURE__*/
  fileDesc("Chttb2RlbC93b3Jrc3BhY2UvaW5ib3gucHJvdG8SCXdvcmtzcGFjZSLgAgoFSW5ib3gSDAoEbmFtZRgBIAEoCRIOCgZzZW5kZXIYAiABKAkSEAoIcmVjZWl2ZXIYAyABKAkSJwoGc3RhdHVzGAQgASgOMhcud29ya3NwYWNlLkluYm94LlN0YXR1cxIvCgtjcmVhdGVfdGltZRgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASIwoEdHlwZRgGIAEoDjIVLndvcmtzcGFjZS5JbmJveC5UeXBlEhgKC2FjdGl2aXR5X2lkGAcgASgFSACIAQEiOgoGU3RhdHVzEhYKElNUQVRVU19VTlNQRUNJRklFRBAAEgoKBlVOUkVBRBABEgwKCEFSQ0hJVkVEEAIiQgoEVHlwZRIUChBUWVBFX1VOU1BFQ0lGSUVEEAASEAoMTUVNT19DT01NRU5UEAESEgoOVkVSU0lPTl9VUERBVEUQAkIOCgxfYWN0aXZpdHlfaWRCPFo6Z2l0aHViLmNvbS9zbWFydG1lbW9zL21lbW9zL2ludGVybmFsL3Byb3RvL21vZGVsL3dvcmtzcGFjZWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message workspace.Inbox
 */
export type Inbox = Message<"workspace.Inbox"> & {
  /**
   * The name of the inbox.
   * Format: inboxes/{id}, id is the system generated auto-incremented id.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Format: users/{user}
   *
   * @generated from field: string sender = 2;
   */
  sender: string;

  /**
   * Format: users/{user}
   *
   * @generated from field: string receiver = 3;
   */
  receiver: string;

  /**
   * @generated from field: workspace.Inbox.Status status = 4;
   */
  status: Inbox_Status;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 5;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: workspace.Inbox.Type type = 6;
   */
  type: Inbox_Type;

  /**
   * @generated from field: optional int32 activity_id = 7;
   */
  activityId?: number;
};

/**
 * Describes the message workspace.Inbox.
 * Use `create(InboxSchema)` to create a new message.
 */
export const InboxSchema: GenMessage<Inbox> = /*@__PURE__*/
  messageDesc(file_model_workspace_inbox, 0);

/**
 * @generated from enum workspace.Inbox.Status
 */
export enum Inbox_Status {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  STATUS_UNSPECIFIED = 0,

  /**
   * @generated from enum value: UNREAD = 1;
   */
  UNREAD = 1,

  /**
   * @generated from enum value: ARCHIVED = 2;
   */
  ARCHIVED = 2,
}

/**
 * Describes the enum workspace.Inbox.Status.
 */
export const Inbox_StatusSchema: GenEnum<Inbox_Status> = /*@__PURE__*/
  enumDesc(file_model_workspace_inbox, 0, 0);

/**
 * @generated from enum workspace.Inbox.Type
 */
export enum Inbox_Type {
  /**
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: MEMO_COMMENT = 1;
   */
  MEMO_COMMENT = 1,

  /**
   * @generated from enum value: VERSION_UPDATE = 2;
   */
  VERSION_UPDATE = 2,
}

/**
 * Describes the enum workspace.Inbox.Type.
 */
export const Inbox_TypeSchema: GenEnum<Inbox_Type> = /*@__PURE__*/
  enumDesc(file_model_workspace_inbox, 0, 1);

