// @generated by protoc-gen-es v2.5.1 with parameter "target=ts"
// @generated from file model/user/setting.proto (package user, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/user/setting.proto.
 */
export const file_model_user_setting: GenFile = /*@__PURE__*/
  fileDesc("Chhtb2RlbC91c2VyL3NldHRpbmcucHJvdG8SBHVzZXIiVAoHU2V0dGluZxIMCgRuYW1lGAEgASgJEg4KBmxvY2FsZRgCIAEoCRISCgphcHBlYXJhbmNlGAMgASgJEhcKD21lbW9fdmlzaWJpbGl0eRgEIAEoCUI3WjVnaXRodWIuY29tL3NtYXJ0bWVtb3MvbWVtb3MvaW50ZXJuYWwvcHJvdG8vbW9kZWwvdXNlcmIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message user.Setting
 */
export type Setting = Message<"user.Setting"> & {
  /**
   * The name of the user.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The preferred locale of the user.
   *
   * @generated from field: string locale = 2;
   */
  locale: string;

  /**
   * The preferred appearance of the user.
   *
   * @generated from field: string appearance = 3;
   */
  appearance: string;

  /**
   * The default visibility of the memo.
   *
   * @generated from field: string memo_visibility = 4;
   */
  memoVisibility: string;
};

/**
 * Describes the message user.Setting.
 * Use `create(SettingSchema)` to create a new message.
 */
export const SettingSchema: GenMessage<Setting> = /*@__PURE__*/
  messageDesc(file_model_user_setting, 0);

