// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file model/user/stats.proto (package user, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file model/user/stats.proto.
 */
export const file_model_user_stats: GenFile = /*@__PURE__*/
  fileDesc("ChZtb2RlbC91c2VyL3N0YXRzLnByb3RvEgR1c2VyIvYCCgVTdGF0cxIMCgRuYW1lGAEgASgJEjsKF21lbW9fZGlzcGxheV90aW1lc3RhbXBzGAIgAygLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIyCg9tZW1vX3R5cGVfc3RhdHMYAyABKAsyGS51c2VyLlN0YXRzLk1lbW9UeXBlU3RhdHMSLAoJdGFnX2NvdW50GAQgAygLMhkudXNlci5TdGF0cy5UYWdDb3VudEVudHJ5EhQKDHBpbm5lZF9tZW1vcxgFIAMoCRIYChB0b3RhbF9tZW1vX2NvdW50GAYgASgFGi8KDVRhZ0NvdW50RW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgFOgI4ARpfCg1NZW1vVHlwZVN0YXRzEhIKCmxpbmtfY291bnQYASABKAUSEgoKY29kZV9jb3VudBgCIAEoBRISCgp0b2RvX2NvdW50GAMgASgFEhIKCnVuZG9fY291bnQYBCABKAVCN1o1Z2l0aHViLmNvbS9zbWFydG1lbW9zL21lbW9zL2ludGVybmFsL3Byb3RvL21vZGVsL3VzZXJiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message user.Stats
 */
export type Stats = Message<"user.Stats"> & {
  /**
   * The name of the user.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The timestamps when the memos were displayed.
   * We should return raw data to the client, and let the client format the data with the user's timezone.
   *
   * @generated from field: repeated google.protobuf.Timestamp memo_display_timestamps = 2;
   */
  memoDisplayTimestamps: Timestamp[];

  /**
   * The stats of memo types.
   *
   * @generated from field: user.Stats.MemoTypeStats memo_type_stats = 3;
   */
  memoTypeStats?: Stats_MemoTypeStats;

  /**
   * The count of tags.
   * Format: "tag1": 1, "tag2": 2
   *
   * @generated from field: map<string, int32> tag_count = 4;
   */
  tagCount: { [key: string]: number };

  /**
   * The pinned memos of the user.
   *
   * @generated from field: repeated string pinned_memos = 5;
   */
  pinnedMemos: string[];

  /**
   * @generated from field: int32 total_memo_count = 6;
   */
  totalMemoCount: number;
};

/**
 * Describes the message user.Stats.
 * Use `create(StatsSchema)` to create a new message.
 */
export const StatsSchema: GenMessage<Stats> = /*@__PURE__*/
  messageDesc(file_model_user_stats, 0);

/**
 * @generated from message user.Stats.MemoTypeStats
 */
export type Stats_MemoTypeStats = Message<"user.Stats.MemoTypeStats"> & {
  /**
   * @generated from field: int32 link_count = 1;
   */
  linkCount: number;

  /**
   * @generated from field: int32 code_count = 2;
   */
  codeCount: number;

  /**
   * @generated from field: int32 todo_count = 3;
   */
  todoCount: number;

  /**
   * @generated from field: int32 undo_count = 4;
   */
  undoCount: number;
};

/**
 * Describes the message user.Stats.MemoTypeStats.
 * Use `create(Stats_MemoTypeStatsSchema)` to create a new message.
 */
export const Stats_MemoTypeStatsSchema: GenMessage<Stats_MemoTypeStats> = /*@__PURE__*/
  messageDesc(file_model_user_stats, 0, 0);

