swagger: "2.0"
info:
  title: model/common.proto
  version: version not set
tags:
  - name: AuthService
  - name: UserService
consumes:
  - application/json
produces:
  - application/json
paths: {}
definitions:
  UserRole:
    type: string
    enum:
      - ROLE_UNSPECIFIED
      - HOST
      - ADMIN
      - USER
    default: ROLE_UNSPECIFIED
  modelState:
    type: string
    enum:
      - STATE_UNSPECIFIED
      - NORMAL
      - ARCHIVED
    default: STATE_UNSPECIFIED
  modelUser:
    type: object
    properties:
      id:
        type: string
        format: int64
      name:
        type: string
      username:
        type: string
      role:
        $ref: '#/definitions/UserRole'
      nickname:
        type: string
      email:
        type: string
      avatarUrl:
        type: string
      description:
        type: string
      password:
        type: string
      state:
        $ref: '#/definitions/modelState'
      createAt:
        type: string
        format: date-time
      updateAt:
        type: string
        format: date-time
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
