swagger: "2.0"
info:
  title: model/common.proto
  version: version not set
tags:
  - name: AuthService
  - name: UserService
consumes:
  - application/json
produces:
  - application/json
paths: {}
definitions:
  CreateSessionRequestPasswordCredentials:
    type: object
    properties:
      username:
        type: string
        description: |-
          The username to sign in with.
          Required field for password-based authentication.
      password:
        type: string
        description: |-
          The password to sign in with.
          Required field for password-based authentication.
    description: Nested message for password-based authentication credentials.
  CreateSessionRequestSSOCredentials:
    type: object
    properties:
      idpId:
        type: integer
        format: int32
        description: |-
          The ID of the SSO provider.
          Required field to identify the SSO provider.
      code:
        type: string
        description: |-
          The authorization code from the SSO provider.
          Required field for completing the SSO flow.
      redirectUri:
        type: string
        description: |-
          The redirect URI used in the SSO flow.
          Required field for security validation.
    description: Nested message for SSO authentication credentials.
  UserRole:
    type: string
    enum:
      - ROLE_UNSPECIFIED
      - HOST
      - ADMIN
      - USER
    default: ROLE_UNSPECIFIED
  UserStatsMemoTypeStats:
    type: object
    properties:
      linkCount:
        type: integer
        format: int32
      codeCount:
        type: integer
        format: int32
      todoCount:
        type: integer
        format: int32
      undoCount:
        type: integer
        format: int32
    description: Memo type statistics.
  modelState:
    type: string
    enum:
      - STATE_UNSPECIFIED
      - NORMAL
      - ARCHIVED
    default: STATE_UNSPECIFIED
  modelUser:
    type: object
    properties:
      id:
        type: string
        format: int64
      name:
        type: string
      username:
        type: string
      role:
        $ref: '#/definitions/UserRole'
      nickname:
        type: string
      email:
        type: string
      avatarUrl:
        type: string
      description:
        type: string
      password:
        type: string
      state:
        $ref: '#/definitions/modelState'
      createAt:
        type: string
        format: date-time
      updateAt:
        type: string
        format: date-time
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  v2CreateSessionResponse:
    type: object
    properties:
      user:
        $ref: '#/definitions/modelUser'
        description: The authenticated user information.
      lastAccessedAt:
        type: string
        format: date-time
        description: |-
          Last time the session was accessed.
          Used for sliding expiration calculation (last_accessed_time + 2 weeks).
  v2GetCurrentSessionResponse:
    type: object
    properties:
      user:
        $ref: '#/definitions/modelUser'
      lastAccessedAt:
        type: string
        format: date-time
        description: |-
          Last time the session was accessed.
          Used for sliding expiration calculation (last_accessed_time + 2 weeks).
  v2UserStats:
    type: object
    properties:
      name:
        type: string
        title: |-
          The resource name of the user whose stats these are.
          Format: users/{user}
      memoDisplayTimestamps:
        type: array
        items:
          type: string
          format: date-time
        description: The timestamps when the memos were displayed.
      memoTypeStats:
        $ref: '#/definitions/UserStatsMemoTypeStats'
        description: The stats of memo types.
      tagCount:
        type: object
        additionalProperties:
          type: integer
          format: int32
        description: The count of tags.
      pinnedMemos:
        type: array
        items:
          type: string
        description: The pinned memos of the user.
      totalMemoCount:
        type: integer
        format: int32
        description: Total memo count.
    title: User statistics messages
